interface=wlan1
driver=nl80211
ssid=sfv-fieldmesh-ext1
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
ht_capab=[HT40][SHORT-GI-20][SHORT-GI-40]
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=sfv-fieldmesh-ext1-2026
country_code=US
